### ISSUE TITLE
Errors installing libxfce4panel-2.0-4

### ISSUE THREAD

**Issue by shadowdragon625** [rozniak/xfce-winxp-tc#127]
Hello, I'm having problems with installing this tc pack. I've been trying to follow the instructions word for word, but once I asked dpkg to install the forked libxfce4panel, it complains about dependency problems, including libgdk-pixbuf-2.0-0 not being installed, but it actually is installed? Even after doing apt --fix-broken install I still keep getting the same results.

I'm relatively new to this whole thing so I apologize if this current issue is not formatted correctly.

**Comment by rozniak** [comment]
What distro are you using?

**Comment by shadowdragon625** [comment]
I've attempted it using Linux Mint, without having installed xfce. Just using cinnamon on it.

**Comment by rozniak** [comment]
Linux Mint Cinnamon Edition? I'll have a look and see what's going on...

**Comment by shadowdragon625** [comment]
It's a fresh install too

**Comment by rozniak** [comment]
Please can you paste the output of `apt list --installed | grep pixbuf` here?

I have been able to get the fork compiled/packaged on a fresh install of Linux Mint Cinnamon Edition so hopefully it's something straight forward that's going on.

**Comment by rozniak** [comment]
Disregard that actually - I think I see what's going on here... the package name on Debian is `libgdk-pixbuf-2.0-0` whereas Mint (which I think is Ubuntu repos?) calls it `libgdk-pixbuf2.0-0`, without the extra dash between the version and the name of the package.

**Comment by rozniak** [comment]
I've updated the submodule so that the Ubuntu package name is treated as an alternative. That seems to have fixed the problem in my testing on Linux Mint.

What you need to do on your side is:
- `cd` back up, so you're in the `xfce-winxp-tc` repo and not the submodule
- `git pull`
- `git submodule update`
- now rerun `./pack-libxfce4panel-2.0.sh` and try installing the outputted package, this time it should pass the dependency checks and allow you to install

Let me know how it goes. :grin:

**Comment by shadowdragon625** [comment]
Apologies for my late reply. I will be trying it out now!

**Comment by shadowdragon625** [comment]
We have success! It still complains about downgrading from 4.16.3-1~20.04 to 4.16.2-1, but doesn't seem to throw any errors.

Thanks a bunch! I can now continue setting this up. What distro did you use to create this transformation pack, just curious.

**Comment by shadowdragon625** [comment]
Whoop, scratch that. xfce4-panel.deb is giving the same error.

**Comment by shadowdragon625** [comment]
Anything that seems to depend on libgdk-pixbuf-2.0-0 and exo-utils (new error that popped up) appears to happen frequently, but even though I have it installed, a simple hyphen completely breaks the setup. Damn you Linux Mint, lol

**Comment by rozniak** [comment]
> We have success! It still complains about downgrading from 4.16.3-1~20.04 to 4.16.2-1, but doesn't seem to throw any errors.

It's been a while since I last pulled changes down from upstream, so I'll need to sort that I expect.

> What distro did you use to create this transformation pack, just curious.

I use Debian 11.

> Whoop, scratch that. xfce4-panel.deb is giving the same error.
> Anything that seems to depend on libgdk-pixbuf-2.0-0 and exo-utils (new error that popped up) appears to happen frequently, but even though I have it installed, a simple hyphen completely breaks the setup. Damn you Linux Mint, lol

I should've checked the panel whilst I was at it. :facepalm: 

This might also be an issue with the Start menu as well as I'm sure it depends on `exo-utils` for opening things like *My Documents* using the default file browser. I'll have a look this evening and do some more testing on Linux Mint and get back to you when I get it working. :+1:

**Comment by rozniak** [comment]
Apparently there's also some compiler errors on Mint, perhaps due to newer GCC so I will look at those as well.

**Comment by rozniak** [comment]
@shadowdragon625

Issues should be resolved now.

There is a quirk with packaging though... you will need to install `libxfce4panel-2.0-dev` and `xfce4-panel` using normal APT first, and then install the forked packages second. The reason being is because the version of the Ubuntu packages seem to have `~20.04` on the end, and it doesn't like that when installing the development headers.

I'm wondering if I need to add a `-dev` package to the fork as well to get around that, but follow the above for now.

`exo-utils` is installable via APT, nothing funny required there.

Also fixed some compiler warnings as well that prevented comgtk and shell-start from building, so all should be working on Linux Mint now. I've been able to install all the packages on my VM.

**Comment by rozniak** [comment]
Will do a bit more work on the fork packaging because it is a bit too bodgy for my liking, it should work but apt won't reaaaaally like the version numbers.

**Comment by rozniak** [comment]
No need to worry about breaking your package manager anymore - I have updated the submodule with some bodges that should prevent that from happening. When you run the `./pack-xxx` scripts, it will look up what the current upstream version is, and use that as the package version. Bit cheeky but it appears to work and APT no longer complains, rejoice!

**Comment by shadowdragon625** [comment]
Awesome, thanks a whole bunch!

I'll go ahead and pull the repo; I'll let you know of anything else. Cheers to you man! Spread the XP love

**Comment by shadowdragon625** [comment]
@rozniak 

All packages have been successfully installed with no problems!

However now, when selecting the Start Button to add to the panel, an error message pops up indicating that "Plugin 'Start button' unexpectedly left the panel, do you want to restart it?"

Pressing Execute does not change anything and the start button plugin does not show up. The systray works completely fine (aside from the default xfce4 panel color peaking through the left of it.

![image](https://user-images.githubusercontent.com/67454590/161453167-5df15476-1f2d-4bac-b73f-356808b57f8a.png)

![image](https://user-images.githubusercontent.com/67454590/161453188-2a02e6d4-7572-42a0-9ff7-37f1424ec4ad.png)

**Comment by rozniak** [comment]
> However now, when selecting the Start Button to add to the panel, an error message pops up indicating that "Plugin 'Start button' unexpectedly left the panel, do you want to restart it?"
>
> Pressing Execute does not change anything and the start button plugin does not show up. 

This means the Start menu plugin is crashing out somehow - I'll have to see if I can reproduce the problem in my VM.

> The systray works completely fine (aside from the default xfce4 panel color peaking through the left of it. Dunno if that's from my end.)

Not sure off the top of my head, I'll have to check this too.

Will have a look tomorrow, it's pretty late here so I'm about to have a kip. :stuck_out_tongue: :sleeping:

**Comment by rozniak** [comment]
I'm not totally familiar with switching from Cinnamon to XFWM4 and whatnot... I tried the setup on Linux Mint XFCE and it looks as expected:
![image](https://user-images.githubusercontent.com/13258281/161628185-f2a2e03e-4251-4012-81d9-10c0bf403ca4.png)

Is it viable to use 'XFCE Edition' or do you need to be able to switch from Cinnamon over to XFCE?

**Comment by shadowdragon625** [comment]
I can switch over to XFCE Edition. I'll see how everything goes from there.

Thank you so much for your help so far man ^^

**Comment by shadowdragon625** [comment]
Okay, so they work now. But the graphical glitches appear to still be there. I have this running on a VM that is set up similar to my Cinnamon build. My panel does not look like yours

![image](https://user-images.githubusercontent.com/67454590/161667501-ee307f21-c050-48ac-b138-ffd015342f5a.png)

Perhaps I'm not installing the correct dependencies?

**Comment by rozniak** [comment]
That looks to me like you haven't got the XFCE panel fork running - the grey panel background is due to a bug in the 4.16 version of the panel (fixed for 4.17). The fork has a fix in it, and also removes that border on the top as well (which isn't a bug, but I have plans to try and submit a patch upstream to make it themable).

**Comment by rozniak** [comment]
BTW with the Cinnamon Edition problem regarding the Start menu - if you still have a system that can produce it, it would be helpful if you could launch the panel from the terminal so you can see perhaps why it's crashing.

Open a terminal and do
```
xfce4-panel -q
xfce4-panel &
```

Then try adding the Start menu plugin - once it pops up with the error, report whatever it has outputted in the terminal. It should mention it tried to add `libstartmenu-plugin.so` but failed with some error.

No worries if you binned the VM/setup you had but if you still have it to hand it would be appreciated to see what's going on with it.

**Comment by shadowdragon625** [comment]
The commands did nothing to fix it.

However, you mentioned the version change of 4.17. I ran the command xfce4-panel --version and it still says 4.16

I've tried rebuilding from the submodule panel branch, still gives me 4.16 in the dpkg.

![image](https://user-images.githubusercontent.com/67454590/161872596-a7a67a69-27ad-48cf-bafa-d70cf452ef92.png)

**Comment by shadowdragon625** [comment]
Perhaps Linux Mint repos do not support xfce4 4.17?

**Comment by rozniak** [comment]
I'm really sorry I confused you - when I mentioned `(fixed for 4.17)`, I meant that I have fixed the bug upstream, and the fix will be included in the future 4.17 version of XFCE. The fork is 4.16-3, with the fix essentially 'backported' - the version you're seeing is correct.

That said, in your screenshot I only see `xfce4-panel.deb`. You also need to run `./pack-libxfce4panel-2.0.sh` as well to package the `libxfce4panel-2.0` library. It's *this* package that has the fix for the grey background bug.

**Comment by shadowdragon625** [comment]
I have uninstalled and reinstalled both packages. The grey background bug still remains

**Comment by rozniak** [comment]
You've definitely installed the `libxfce4panel-2.0` forked package, and restarted the panel?

**Comment by shadowdragon625** [comment]
Absolutely.

I removed both packages and purged them, just in case.

I install the library package first, using sudo apt update and upgrade. Then the panel. I start it, and the graphical glitch is still there.

**Comment by rozniak** [comment]
> I install the library package first, using sudo apt update and upgrade.

The commands are:
```
./pack-libxfce4panel-2.0.sh
sudo dpkg -i libxfce4panel-2.0-4.deb
./pack-xfce4-panel.sh
sudo dpkg -i xfce4-panel.deb
```

**Comment by shadowdragon625** [comment]
Yes I did those. Used xfce4-panel -q to close, and then reopen, same exact gray background.

I'm not entirely sure what's happening so what I'm going to try to do is make another VM and start from scratch, and just worry about getting the panel and the plugins to work. Could just be me installing the wrong dependencies before running the pack commands. Maybe that could be it?

**Comment by rozniak** [comment]
If it helps you troubleshoot - it's definitely the `libxfce4panel-2.0-4` forked package that has the patched grey background bug.
