### ISSUE TITLE
taskband - Task buttons extend outside of allocated area

### ISSUE THREAD

**Issue by thepenguin-bird** [rozniak/xfce-winxp-tc#539]
<img width="1438" height="60" alt="Image" src="https://github.com/user-attachments/assets/70770371-be4d-457e-b5ff-d527e423f9c1" />

**Comment by TuffCWC** [comment]
This is fixed  on other themes, kinda weird

**Comment by rozniak** [comment]
I had a theory in this comment, I need to investigate it: https://github.com/rozniak/xfce-winxp-tc/issues/405#issuecomment-2571644916

**Comment by TuffCWC** [comment]
thanks for your reply, and the theory makes sense, the only reason i use classic is because i hate luna, it looks like a fisher price toy

**Comment by rozniak** [comment]
I think it's only from changing the theme, it doesn't update the widget allocations correctly. Killing and relaunching the taskband should resolve it iirc.

**Comment by TuffCWC** [comment]
Nope, Still the same problem, even after killing and relaunching the taskband

**Comment by rozniak** [comment]
Guess that makes sense now that I think about it. Thanks for the report I'd forgotten about this problem since that issue comment!

**Comment by rozniak** [comment]
Incredibly stupid, I did actually deal with the margins... aside from setting a variable for working out the last step of allocating the button widths. Latest build of `shell/taskband` should be fixed.

**Comment by TuffCWC** [comment]
Thanks.
